
server:
  port: 0
# 0?? ??? ????

spring:
  application:
    name: catalog-service
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      defer-datasource-initialization: true




eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:
    tobyspring.catalogservice: DEBUG

#      discovery??
# ??? ????? ??
