server:
  port: 8888

spring:
  application:
    name: config-server


  cloud:
      config:
        server:
          git:
            uri: https://github.com/aksenaksen/cloud-config.git
#            username:
#            password:
#  private 변경시
#            uri: file:///C:/Users/user/Desktop/ecoomerce/config