server:
  port: 8888

spring:
  application:
    name: config-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


  cloud:
      config:
        server:
          git:
            uri: https://github.com/aksenaksen/cloud-config.git
            default-label: master
            username: aksenaksen
            password: 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
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
#            username:
#            password:
#  private 변경시
#            uri: file:///C:/Users/user/Desktop/ecoomerce/config